name: hexaminate
description: Hexaminate library.
version: 0.0.8
homepage: https://github.com/HexaMinate/HexaMinate/tree/main/library/hexaminate/docs
repository: https://github.com/HexaMinate/HexaMinate/tree/main/library/hexaminate
issue_tracker: https://github.com/HexaMinate/HexaMinate/issues

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0