name: hexaminate
description: HexaMinate library for create app flutter more easy and lightweight, becouse this not required other library.
version: 0.1.4
homepage: https://github.com/HexaMinate/HexaMinate/tree/main/library/hexaminate
repository: https://github.com/HexaMinate/HexaMinate/tree/main/library/hexaminate
issue_tracker: https://github.com/HexaMinate/HexaMinate/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
dependencies:
  http: ^0.13.4
  universal_io: ^2.0.4
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  http_multi_server: ^3.2.1
  shelf: ^1.3.1
