name: hexaminate_flutter
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  flutter:
    sdk: flutter
  hexaminate: ^0.1.4
  simulate: ^0.0.8
